development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: matsumoto
  password: engenharia

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: matsumoto
  password: engenharia